### PR TITLE
feat: [SIW-279] Add jwt decode function

### PR DESCRIPTION
**Pull request by grausof**
## Short description
Added JWT decoding using native libraries. The use of native libraries greatly speeds up decoding and signature verification operations.

Uses:
- iOS: [JOSESwift](https://github.com/airsidemobile/JOSESwift/)
- Android: [nimbus-jose-jwt
](https://connect2id.com/products/nimbus-jose-jwt)

## List of changes proposed in this pull request
- Added JWT decode
- Added JWT and JWK types
- Added iOS and Android native library

## How to test
You can use the sample app or install the following package in another app. The package is not yet published to npm so you can add the dependency to the repo or create a package with the `yarn pack` command.

This library does not require any dependencies to be installed in the app that uses it!

### CODE REVIEW

**Review by hevelius — APPROVED** [review]
LGTM Tested on iOS simulator. Well done! Just a note about the repository name. Under pagopa ecosystem we have others rn libraries named as `io-react-native-*`. What do you think about using same pattern?

**Comment by grausof** [comment]
> LGTM Tested on iOS simulator. Well done! Just a note about the repository name. Under pagopa ecosystem we have others rn libraries named as `io-react-native-*`. What do you think about using same pattern?

Yes correct. I'll try to rename it!

**Comment by balanza** [comment]
> LGTM Tested on iOS simulator. Well done! Just a note about the repository name. Under pagopa ecosystem we have others rn libraries named as `io-react-native-*`. What do you think about using same pattern?

Sorry, I'm late on review. `io-` suppose this package makes sense on `IO` only. Does it?

**Comment by grausof** [comment]
> > LGTM Tested on iOS simulator. Well done! Just a note about the repository name. Under pagopa ecosystem we have others rn libraries named as `io-react-native-*`. What do you think about using same pattern?
> 
> Sorry, I'm late on review. `io-` suppose this package makes sense on `IO` only. Does it?

This repo also has nothing in common with IO but has been renamed like [io-react-native-crypto](https://github.com/pagopa/io-react-native-crypto)

**Pull request merged**
